name:                kalapala
version:             0.1.0.0
github:              "mucla/kalapala"
license:             BSD3
author:              "M Koivuniemi"
maintainer:          "mucla@iki.fi"
copyright:           "2022 M Koivuniemi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mucla/kalapala#readme>

dependencies:
- base >= 4.7 && < 5
- gloss

library:
  source-dirs: src

executables:
  kalapala:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kalapala

tests:
  kalapala-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kalapala
